namespace: ci-cd
name: jenkins-helm
image: jfrog.it-academy.by/public/jenkins-ci:ermakov

nfs_path: /mnt/IT-Academy/nfs-data/sa2-21-22/ermakov/jenkins
nfs_server: 192.168.37.105

admin_address: evgeniermakov1994@gmail.com

ingress:
  enabled: enabled
server_alias: "jenkins-helm.k8s-10.sa"
web_host: jenkins-helm.k8s-9.sa
ingress_port: 8080
main_host_url: http://jenkins-helm.k8s-10.sa/

resources:
  limits:
    cpu: 3100m
    memory: 4100Mi
  requests:
    cpu: 3100m
    memory: 3100Mi

master_port: 8080
master_targetport: 8080
slave_port: 50000
slave_targetport: 50000 

